--------------------------------------------------------
-- Archivo creado  - viernes-noviembre-15-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for DB Link LINK_TO_SERVER_1
--------------------------------------------------------

  CREATE DATABASE LINK "LINK_TO_SERVER_1"
   CONNECT TO "COMPUTO" IDENTIFIED BY VALUES '0559973C0CFE07E4CFA5520CA80A828791'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=d39909a09c67)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))'
--------------------------------------------------------
--  DDL for DB Link LINK_TO_SERVER_2
--------------------------------------------------------

  CREATE DATABASE LINK "LINK_TO_SERVER_2"
   CONNECT TO "COMPUTO2" IDENTIFIED BY VALUES '0529E23190F68AE7AF5B30749C3D5DA4AFB4495CD9C6D98C60'
   USING '(DESCRIPTION=
          (ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1522))
          (CONNECT_DATA=(SERVICE_NAME=oracle_db2))
        )'
--------------------------------------------------------
--  DDL for DB Link SITE_A_LINK
--------------------------------------------------------

  CREATE DATABASE LINK "SITE_A_LINK"
   CONNECT TO "COMPUTO" IDENTIFIED BY VALUES '05AFBFEB8AF8939EFC108874EA009F9776'
   USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=d39909a09c67)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))'
--------------------------------------------------------
--  DDL for Table EMPLEADOS_B
--------------------------------------------------------

  CREATE TABLE "COMPUTO2"."EMPLEADOS_B" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50), 
	"DEPARTAMENTO" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PRESTAMO_B
--------------------------------------------------------

  CREATE TABLE "COMPUTO2"."PRESTAMO_B" 
   (	"NOPRESTAMO" VARCHAR2(15) NOT NULL ENABLE, 
	"IDSUCURSAL" VARCHAR2(5), 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table PRUEBA_B
--------------------------------------------------------

  CREATE TABLE "COMPUTO2"."PRUEBA_B" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SUCURSAL_B
--------------------------------------------------------

  CREATE TABLE "COMPUTO2"."SUCURSAL_B" 
   (	"IDSUCURSAL" VARCHAR2(5) NOT NULL ENABLE, 
	"NOMBRESUCURSAL" VARCHAR2(15), 
	"CIUDADSUCURSAL" VARCHAR2(15), 
	"ACTIVOS" NUMBER, 
	"REGION" VARCHAR2(2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for View PRESTAMO_GLOBAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMPUTO2"."PRESTAMO_GLOBAL" ("NOPRESTAMO", "IDSUCURSAL", "CANTIDAD") AS 
  SELECT "NOPRESTAMO","IDSUCURSAL","CANTIDAD" FROM prestamo_b
UNION ALL
SELECT "NOPRESTAMO","IDSUCURSAL","CANTIDAD" FROM prestamo_a@site_a_link
--------------------------------------------------------
--  DDL for View SUCURSAL_GLOBAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "COMPUTO2"."SUCURSAL_GLOBAL" ("IDSUCURSAL", "NOMBRESUCURSAL", "CIUDADSUCURSAL", "ACTIVOS", "REGION") AS 
  SELECT "IDSUCURSAL","NOMBRESUCURSAL","CIUDADSUCURSAL","ACTIVOS","REGION" FROM sucursal_b
UNION ALL
SELECT "IDSUCURSAL","NOMBRESUCURSAL","CIUDADSUCURSAL","ACTIVOS","REGION" FROM sucursal_a@site_a_link
--------------------------------------------------------
--  DDL for Materialized View MV_PRESTAMO_GLOBAL
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "COMPUTO2"."MV_PRESTAMO_GLOBAL" ("NOPRESTAMO", "IDSUCURSAL", "CANTIDAD")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT * FROM prestamo_global

   COMMENT ON MATERIALIZED VIEW "COMPUTO2"."MV_PRESTAMO_GLOBAL"  IS 'snapshot table for snapshot COMPUTO2.MV_PRESTAMO_GLOBAL'
--------------------------------------------------------
--  DDL for Materialized View VISTA_EMPLEADOS_A
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "COMPUTO2"."VISTA_EMPLEADOS_A" ("ID", "NOMBRE", "PUESTO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
  REFRESH COMPLETE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT id, nombre, puesto FROM empleados_a@link_to_server_1

   COMMENT ON MATERIALIZED VIEW "COMPUTO2"."VISTA_EMPLEADOS_A"  IS 'snapshot table for snapshot COMPUTO2.VISTA_EMPLEADOS_A'
REM INSERTING into COMPUTO2.EMPLEADOS_B
SET DEFINE OFF;
Insert into COMPUTO2.EMPLEADOS_B (ID,NOMBRE,DEPARTAMENTO) values (1,'Carlos Lopez','Recursos Humanos');
Insert into COMPUTO2.EMPLEADOS_B (ID,NOMBRE,DEPARTAMENTO) values (2,'Ana Martinez','Marketing');
Insert into COMPUTO2.EMPLEADOS_B (ID,NOMBRE,DEPARTAMENTO) values (3,'Luis Perez','Finanzas');
Insert into COMPUTO2.EMPLEADOS_B (ID,NOMBRE,DEPARTAMENTO) values (4,'Maria Gomez','Contadora');
Insert into COMPUTO2.EMPLEADOS_B (ID,NOMBRE,DEPARTAMENTO) values (5,'Poncho Manuel','Chalan');
REM INSERTING into COMPUTO2.PRESTAMO_B
SET DEFINE OFF;
Insert into COMPUTO2.PRESTAMO_B (NOPRESTAMO,IDSUCURSAL,CANTIDAD) values ('L-11','S0005',900);
Insert into COMPUTO2.PRESTAMO_B (NOPRESTAMO,IDSUCURSAL,CANTIDAD) values ('L-20','S0007',7500);
Insert into COMPUTO2.PRESTAMO_B (NOPRESTAMO,IDSUCURSAL,CANTIDAD) values ('L-21','S0009',570);
REM INSERTING into COMPUTO2.PRUEBA_B
SET DEFINE OFF;
Insert into COMPUTO2.PRUEBA_B (ID,DESCRIPCION) values (2,'Prueba desde Procedimiento');
Insert into COMPUTO2.PRUEBA_B (ID,DESCRIPCION) values (1,'Prueba desde A');
REM INSERTING into COMPUTO2.SUCURSAL_B
SET DEFINE OFF;
Insert into COMPUTO2.SUCURSAL_B (IDSUCURSAL,NOMBRESUCURSAL,CIUDADSUCURSAL,ACTIVOS,REGION) values ('S0005','Round Hill','Horseneck',8000000,'B');
Insert into COMPUTO2.SUCURSAL_B (IDSUCURSAL,NOMBRESUCURSAL,CIUDADSUCURSAL,ACTIVOS,REGION) values ('S0006','Pownal','Bennington',400000,'B');
Insert into COMPUTO2.SUCURSAL_B (IDSUCURSAL,NOMBRESUCURSAL,CIUDADSUCURSAL,ACTIVOS,REGION) values ('S0007','North Town','Rye',3700000,'B');
Insert into COMPUTO2.SUCURSAL_B (IDSUCURSAL,NOMBRESUCURSAL,CIUDADSUCURSAL,ACTIVOS,REGION) values ('S0008','Brighton','Brooklyn',7000000,'B');
Insert into COMPUTO2.SUCURSAL_B (IDSUCURSAL,NOMBRESUCURSAL,CIUDADSUCURSAL,ACTIVOS,REGION) values ('S0009','Central','Rye',400280,'B');
--------------------------------------------------------
--  DDL for Synonymn PRESTAMO_A
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "COMPUTO2"."PRESTAMO_A" FOR "PRESTAMO_A"@"SITE_A_LINK"
--------------------------------------------------------
--  DDL for Synonymn SUCURSAL_A
--------------------------------------------------------

  CREATE OR REPLACE SYNONYM "COMPUTO2"."SUCURSAL_A" FOR "SUCURSAL_A"@"SITE_A_LINK"
--------------------------------------------------------
--  Constraints for Table PRESTAMO_B
--------------------------------------------------------

  ALTER TABLE "COMPUTO2"."PRESTAMO_B" MODIFY ("NOPRESTAMO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table EMPLEADOS_B
--------------------------------------------------------

  ALTER TABLE "COMPUTO2"."EMPLEADOS_B" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table PRUEBA_B
--------------------------------------------------------

  ALTER TABLE "COMPUTO2"."PRUEBA_B" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table SUCURSAL_B
--------------------------------------------------------

  ALTER TABLE "COMPUTO2"."SUCURSAL_B" MODIFY ("IDSUCURSAL" NOT NULL ENABLE)
